Update for RGB
Minecrell/TerminalConsoleAppender pull request #17
Opened 2020-09-04 17:18 UTC by Narimm

Updates to support rgb

2020-09-05 16:22 UTC, Mystiflow requested changes

2020-09-05 16:22 UTC, Mystiflow commented on src/main/java/net/minecrell/terminalconsole/MinecraftFormattingConverter.java
> +            String escCode = ansiCodes.get(color);
This could be changed with looping ansiCodes.entrySet instead.

2020-09-05 16:22 UTC, Mystiflow commented on src/test/java/net/minecrell/terminalconsole/MinecraftFormattingConverterTest.java
> +
Empty line

2020-09-06 22:41 UTC, Narimm commented
https://github.com/PaperMC/Paper/pull/4221

2020-09-06 22:46 UTC, zml2008 commented
I'm not a fan of adding support for spigot's non-standard format directly to TCA -- a TCA PR should really just remove TCA's dependence on MC's legacy text formatting.

2020-09-07 05:31 UTC, Narimm commented
> I'm not a fan of adding support for spigot's non-standard format directly to TCA -- a TCA PR should really just remove TCA's dependence on MC's legacy text formatting.

What if Paper forks TCA

2020-09-09 19:24 UTC, zml2008 commented
I'd really rather not -- a number of projects use TCA -- forge for one -- so any improvements made should really be designed to benefit them as well.

2020-09-14 11:33 UTC, Minecrell commented
I agree with @zml2008. Unless other projects like Sponge, Forge, ... agree on the same convention I would rather not support the non-standard Spigot format here.

Actually, the only reason `MinecraftFormattingConverter` exists in TerminalConsoleAppender at all is that back when I integrated better console support into Paper/Forge/SpongeVanilla/... all the projects needed exactly the same and I did not want to duplicate the code everywhere. In general, TCA is supposed to entirely independent of Minecraft so preferably Minecraft-specific code should not be here at all.

If the code can no longer be shared in a reasonable way it's really better to just put special converters into the projects itself - there is really not much of a difference because it's so easy to hook into Log4j2 with the annotations.

2020-10-08 19:22 UTC, electronicboy commented
>  the code can no longer be shared in a reasonable way it's really better to just put special converters into the projects itself - there is really not much of a difference because it's so easy to hook into Log4j2 with the annotations

I'm inclined to ask for this, 'lest I go break the existing log4j configs people are using to add a bukkit RGB aware impl of this class

2021-05-07 19:13 UTC, Minecrell commented
For the reasons already mentioned above (and also mentioned in https://github.com/Minecrell/TerminalConsoleAppender/issues/18) I will close this. However, @Narimm thanks a lot for making the PR! I believe something like your code made it into Paper as part of https://github.com/PaperMC/Paper/pull/5205.

As inspiration for all others who also want to add RGB console color to their platform, I've also documented a potential quite different approach in https://github.com/Minecrell/TerminalConsoleAppender/issues/18 that would avoid legacy color codes entirely. I think this would be the ideal solution but I don't really have time at the moment to investigate it myself.

2021-05-07 19:13 UTC, closed without merging